baseURL = "https://deveganeetclub.nl"
title   = "deveganeetclub recepten"
theme   = "cuisine-book"

enableGitInfo = true

[params]
  author      = "Daniël Geerts"
  description = "A collection of our favourite recipes, by deveganeetclub community"
  logo        = "logo.jpg"
  repo        = "https://github.com/devdanielsun/deveganeetclub"
  editpath    = "edit/master"
  newpath     = "new/master"

[[menu.main]]
  name   = "Home"
  url    = "/"
  weight = 1

[[menu.main]]
  name   = "Over Ons"
  url    = "/over-ons/"
  weight = 2