baseURL = "https://deveganeetclub.nl"
title = "deveganeetclub recepten"
enableGitInfo = true

[params]
  author = "Daniël Geerts"
  description = "A collection of our favourite recipes, by deveganeetclub community"
  repo = "https://github.com/devdanielsun/deveganeetclub"
  editpath = "edit/master"
  newpath = "new/master"
